const PALETTES = {
  "light-spring": {
    name: "Light Spring",
    aliases: ["Bright Spring Light"],
    description: "Warm, light, and clear. Think peach, coral, golden yellow.",
    colors: [
      { hex: "#F5D6C3", name: "Peach Cream" },
      { hex: "#FADADD", name: "Light Pink" },
      { hex: "#FF9980", name: "Salmon" },
      { hex: "#FF6F61", name: "Coral" },
      { hex: "#FFB347", name: "Apricot" },
      { hex: "#FFD700", name: "Golden Yellow" },
      { hex: "#FFFACD", name: "Lemon Chiffon" },
      { hex: "#98FB98", name: "Mint Green" },
      { hex: "#7EC8A0", name: "Spring Green" },
      { hex: "#87CEEB", name: "Sky Blue" },
      { hex: "#B0E0E6", name: "Powder Blue" },
      { hex: "#DDA0DD", name: "Light Plum" },
      { hex: "#E6C2DC", name: "Orchid Pink" },
      { hex: "#F0E68C", name: "Khaki" },
      { hex: "#FFDEAD", name: "Navajo White" },
      { hex: "#D2B48C", name: "Tan" },
      { hex: "#F5F5DC", name: "Beige" },
      { hex: "#FFFDD0", name: "Cream" },
      { hex: "#FAEBD7", name: "Antique White" },
      { hex: "#C9A96E", name: "Warm Gold" },
      { hex: "#FFC0CB", name: "Pink" },
      { hex: "#E0BBE4", name: "Lavender" },
      { hex: "#77DD77", name: "Pastel Green" },
      { hex: "#AEC6CF", name: "Pastel Blue" },
      { hex: "#FFE5B4", name: "Peach" },
      { hex: "#F4A460", name: "Sandy Brown" },
      { hex: "#CD853F", name: "Peru" },
      { hex: "#DAA520", name: "Goldenrod" },
      { hex: "#40E0D0", name: "Turquoise" },
      { hex: "#FA8072", name: "Light Coral" }
    ]
  },
  "warm-spring": {
    name: "Warm Spring",
    aliases: ["True Spring"],
    description: "Warm, medium-light, and clear. Rich warm tones.",
    colors: [
      { hex: "#FF6347", name: "Tomato Red" },
      { hex: "#FF4500", name: "Orange Red" },
      { hex: "#FF8C00", name: "Dark Orange" },
      { hex: "#FFA500", name: "Orange" },
      { hex: "#FFD700", name: "Gold" },
      { hex: "#F0E130", name: "Yellow" },
      { hex: "#ADFF2F", name: "Green Yellow" },
      { hex: "#7CFC00", name: "Lawn Green" },
      { hex: "#32CD32", name: "Lime Green" },
      { hex: "#00CED1", name: "Dark Turquoise" },
      { hex: "#40E0D0", name: "Turquoise" },
      { hex: "#48D1CC", name: "Medium Turquoise" },
      { hex: "#FF7F50", name: "Coral" },
      { hex: "#E9967A", name: "Dark Salmon" },
      { hex: "#F4A460", name: "Sandy Brown" },
      { hex: "#DEB887", name: "Burlywood" },
      { hex: "#D2691E", name: "Chocolate" },
      { hex: "#8B4513", name: "Saddle Brown" },
      { hex: "#A0522D", name: "Sienna" },
      { hex: "#CD853F", name: "Peru" },
      { hex: "#DAA520", name: "Goldenrod" },
      { hex: "#B8860B", name: "Dark Goldenrod" },
      { hex: "#F5DEB3", name: "Wheat" },
      { hex: "#FFDEAD", name: "Navajo White" },
      { hex: "#FFE4B5", name: "Moccasin" },
      { hex: "#FFFACD", name: "Lemon Chiffon" },
      { hex: "#FAFAD2", name: "Light Goldenrod" },
      { hex: "#EEE8AA", name: "Pale Goldenrod" },
      { hex: "#BDB76B", name: "Dark Khaki" },
      { hex: "#556B2F", name: "Dark Olive" }
    ]
  },
  "clear-spring": {
    name: "Clear Spring",
    aliases: ["Bright Spring"],
    description: "Warm, bright, and high-contrast. Vivid warm colors.",
    colors: [
      { hex: "#FF0000", name: "Bright Red" },
      { hex: "#FF4500", name: "Orange Red" },
      { hex: "#FF6600", name: "Vivid Orange" },
      { hex: "#FFCC00", name: "Vivid Yellow" },
      { hex: "#00FF00", name: "Bright Green" },
      { hex: "#00CC99", name: "Caribbean Green" },
      { hex: "#00BFFF", name: "Deep Sky Blue" },
      { hex: "#1E90FF", name: "Dodger Blue" },
      { hex: "#4169E1", name: "Royal Blue" },
      { hex: "#FF1493", name: "Deep Pink" },
      { hex: "#FF69B4", name: "Hot Pink" },
      { hex: "#FF7F50", name: "Coral" },
      { hex: "#FFA07A", name: "Light Salmon" },
      { hex: "#FFD700", name: "Gold" },
      { hex: "#F0E68C", name: "Khaki" },
      { hex: "#7FFF00", name: "Chartreuse" },
      { hex: "#00FA9A", name: "Medium Spring" },
      { hex: "#20B2AA", name: "Light Sea Green" },
      { hex: "#87CEEB", name: "Sky Blue" },
      { hex: "#6495ED", name: "Cornflower Blue" },
      { hex: "#9370DB", name: "Medium Purple" },
      { hex: "#BA55D3", name: "Medium Orchid" },
      { hex: "#F5F5DC", name: "Beige" },
      { hex: "#FFFFF0", name: "Ivory" },
      { hex: "#FFDAB9", name: "Peach Puff" },
      { hex: "#D2B48C", name: "Tan" },
      { hex: "#8B7355", name: "Warm Brown" },
      { hex: "#2E8B57", name: "Sea Green" },
      { hex: "#008B8B", name: "Dark Cyan" },
      { hex: "#191970", name: "Midnight Navy" }
    ]
  },
  "light-summer": {
    name: "Light Summer",
    aliases: ["Fair Summer"],
    description: "Cool, light, and soft. Pastel and dusty cool tones.",
    colors: [
      { hex: "#E6E6FA", name: "Lavender" },
      { hex: "#D8BFD8", name: "Thistle" },
      { hex: "#DDA0DD", name: "Plum" },
      { hex: "#E0B0FF", name: "Mauve" },
      { hex: "#C8A2C8", name: "Lilac" },
      { hex: "#B0C4DE", name: "Light Steel Blue" },
      { hex: "#87CEEB", name: "Sky Blue" },
      { hex: "#ADD8E6", name: "Light Blue" },
      { hex: "#B0E0E6", name: "Powder Blue" },
      { hex: "#AFEEEE", name: "Pale Turquoise" },
      { hex: "#E0FFFF", name: "Light Cyan" },
      { hex: "#F0FFF0", name: "Honeydew" },
      { hex: "#98FB98", name: "Pale Green" },
      { hex: "#8FBC8F", name: "Dark Sea Green" },
      { hex: "#FFC0CB", name: "Pink" },
      { hex: "#FFB6C1", name: "Light Pink" },
      { hex: "#F4C2C2", name: "Baby Pink" },
      { hex: "#FADADD", name: "Pale Pink" },
      { hex: "#E8CCD7", name: "Queen Pink" },
      { hex: "#C9C0BB", name: "Silver Pink" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#A9A9A9", name: "Dark Gray" },
      { hex: "#D3D3D3", name: "Light Gray" },
      { hex: "#F5F5F5", name: "White Smoke" },
      { hex: "#FFFAFA", name: "Snow" },
      { hex: "#F0F0E0", name: "Soft Cream" },
      { hex: "#CDB7B5", name: "Misty Rose" },
      { hex: "#BC8F8F", name: "Rosy Brown" },
      { hex: "#A9B2C3", name: "Cool Gray" },
      { hex: "#6A5ACD", name: "Slate Blue" }
    ]
  },
  "cool-summer": {
    name: "Cool Summer",
    aliases: ["True Summer"],
    description: "Cool, medium, and soft. Blue-based tones with gentle contrast.",
    colors: [
      { hex: "#4682B4", name: "Steel Blue" },
      { hex: "#5F9EA0", name: "Cadet Blue" },
      { hex: "#6495ED", name: "Cornflower Blue" },
      { hex: "#4169E1", name: "Royal Blue" },
      { hex: "#0000CD", name: "Medium Blue" },
      { hex: "#191970", name: "Midnight Blue" },
      { hex: "#708090", name: "Slate Gray" },
      { hex: "#778899", name: "Light Slate Gray" },
      { hex: "#B0C4DE", name: "Light Steel Blue" },
      { hex: "#87CEFA", name: "Light Sky Blue" },
      { hex: "#00CED1", name: "Dark Turquoise" },
      { hex: "#5B8A8A", name: "Teal Blue" },
      { hex: "#7B68EE", name: "Medium Slate Blue" },
      { hex: "#6A5ACD", name: "Slate Blue" },
      { hex: "#9370DB", name: "Medium Purple" },
      { hex: "#8B008B", name: "Dark Magenta" },
      { hex: "#800080", name: "Purple" },
      { hex: "#C71585", name: "Medium Violet Red" },
      { hex: "#DB7093", name: "Pale Violet Red" },
      { hex: "#FFB6C1", name: "Light Pink" },
      { hex: "#DDA0DD", name: "Plum" },
      { hex: "#E6E6FA", name: "Lavender" },
      { hex: "#F0F8FF", name: "Alice Blue" },
      { hex: "#F5F5F5", name: "White Smoke" },
      { hex: "#DCDCDC", name: "Gainsboro" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#808080", name: "Gray" },
      { hex: "#696969", name: "Dim Gray" },
      { hex: "#2F4F4F", name: "Dark Slate Gray" },
      { hex: "#BC8F8F", name: "Rosy Brown" }
    ]
  },
  "soft-summer": {
    name: "Soft Summer",
    aliases: ["Muted Summer", "Deep Summer"],
    description: "Cool, soft, and muted. Dusty, greyed-out cool tones.",
    colors: [
      { hex: "#8E8E8E", name: "Medium Gray" },
      { hex: "#A9A9A9", name: "Dark Gray" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#B0A99F", name: "Warm Gray" },
      { hex: "#8B8589", name: "Taupe Gray" },
      { hex: "#967969", name: "Dark Taupe" },
      { hex: "#C4AEAD", name: "Silver Pink" },
      { hex: "#BC8F8F", name: "Rosy Brown" },
      { hex: "#CD9B9B", name: "Dusty Rose" },
      { hex: "#C08081", name: "Old Rose" },
      { hex: "#B5651D", name: "Cocoa" },
      { hex: "#A0785A", name: "Chamois" },
      { hex: "#808000", name: "Olive" },
      { hex: "#6B8E23", name: "Olive Drab" },
      { hex: "#556B2F", name: "Dark Olive Green" },
      { hex: "#8FBC8F", name: "Dark Sea Green" },
      { hex: "#5F9EA0", name: "Cadet Blue" },
      { hex: "#4682B4", name: "Steel Blue" },
      { hex: "#5C6B73", name: "Stormy Blue" },
      { hex: "#36454F", name: "Charcoal" },
      { hex: "#708090", name: "Slate Gray" },
      { hex: "#6A5ACD", name: "Slate Blue" },
      { hex: "#9370DB", name: "Medium Purple" },
      { hex: "#8B7D82", name: "Dusty Mauve" },
      { hex: "#7B6A8A", name: "Muted Purple" },
      { hex: "#9C8AA5", name: "Dusty Lavender" },
      { hex: "#E6E0D4", name: "Soft Cream" },
      { hex: "#C9C0BB", name: "Pale Taupe" },
      { hex: "#465945", name: "Deep Sage" },
      { hex: "#2F4F4F", name: "Dark Slate" }
    ]
  },
  "deep-autumn": {
    name: "Deep Autumn",
    aliases: ["Dark Autumn"],
    description: "Warm, deep, and rich. Intense warm darks.",
    colors: [
      { hex: "#8B0000", name: "Dark Red" },
      { hex: "#A52A2A", name: "Brown" },
      { hex: "#800000", name: "Maroon" },
      { hex: "#B22222", name: "Firebrick" },
      { hex: "#CC5500", name: "Burnt Orange" },
      { hex: "#D2691E", name: "Chocolate" },
      { hex: "#8B4513", name: "Saddle Brown" },
      { hex: "#654321", name: "Dark Brown" },
      { hex: "#3B2F2F", name: "Dark Chocolate" },
      { hex: "#556B2F", name: "Dark Olive Green" },
      { hex: "#2E8B57", name: "Sea Green" },
      { hex: "#006400", name: "Dark Green" },
      { hex: "#004D40", name: "Deep Teal" },
      { hex: "#008080", name: "Teal" },
      { hex: "#1C3A3A", name: "Deep Teal Dark" },
      { hex: "#191970", name: "Midnight Blue" },
      { hex: "#000080", name: "Navy" },
      { hex: "#2F4F4F", name: "Dark Slate Gray" },
      { hex: "#483C32", name: "Dark Taupe" },
      { hex: "#704214", name: "Sepia" },
      { hex: "#996515", name: "Golden Brown" },
      { hex: "#DAA520", name: "Goldenrod" },
      { hex: "#B8860B", name: "Dark Goldenrod" },
      { hex: "#CD853F", name: "Peru" },
      { hex: "#DEB887", name: "Burlywood" },
      { hex: "#F5DEB3", name: "Wheat" },
      { hex: "#FAEBD7", name: "Antique White" },
      { hex: "#6B3A2A", name: "Rust Brown" },
      { hex: "#4A0E0E", name: "Oxblood" },
      { hex: "#3C1414", name: "Deep Burgundy" }
    ]
  },
  "warm-autumn": {
    name: "Warm Autumn",
    aliases: ["True Autumn"],
    description: "Warm, medium, and muted. Earthy, rich warm tones.",
    colors: [
      { hex: "#CC5500", name: "Burnt Orange" },
      { hex: "#E2725B", name: "Terracotta" },
      { hex: "#C04000", name: "Mahogany" },
      { hex: "#B7410E", name: "Rust" },
      { hex: "#A0522D", name: "Sienna" },
      { hex: "#D2691E", name: "Chocolate" },
      { hex: "#CD853F", name: "Peru" },
      { hex: "#DAA520", name: "Goldenrod" },
      { hex: "#B8860B", name: "Dark Goldenrod" },
      { hex: "#808000", name: "Olive" },
      { hex: "#6B8E23", name: "Olive Drab" },
      { hex: "#556B2F", name: "Dark Olive Green" },
      { hex: "#8B4513", name: "Saddle Brown" },
      { hex: "#654321", name: "Dark Brown" },
      { hex: "#DEB887", name: "Burlywood" },
      { hex: "#D2B48C", name: "Tan" },
      { hex: "#C19A6B", name: "Camel" },
      { hex: "#F5DEB3", name: "Wheat" },
      { hex: "#FAEBD7", name: "Antique White" },
      { hex: "#FFF8DC", name: "Cornsilk" },
      { hex: "#FFE4B5", name: "Moccasin" },
      { hex: "#FFDEAD", name: "Navajo White" },
      { hex: "#E9967A", name: "Dark Salmon" },
      { hex: "#F4A460", name: "Sandy Brown" },
      { hex: "#8FBC8F", name: "Dark Sea Green" },
      { hex: "#2E8B57", name: "Sea Green" },
      { hex: "#008080", name: "Teal" },
      { hex: "#704214", name: "Sepia" },
      { hex: "#B5651D", name: "Light Brown" },
      { hex: "#483C32", name: "Dark Taupe" }
    ]
  },
  "soft-autumn": {
    name: "Soft Autumn",
    aliases: ["Muted Autumn"],
    description: "Warm-neutral, soft, and muted. Dusty warm earth tones.",
    colors: [
      { hex: "#C9B79C", name: "Sand" },
      { hex: "#C4AEAD", name: "Silver Pink" },
      { hex: "#BC8F8F", name: "Rosy Brown" },
      { hex: "#B0A99F", name: "Warm Gray" },
      { hex: "#A0785A", name: "Fawn" },
      { hex: "#967969", name: "Dark Taupe" },
      { hex: "#8B8378", name: "Warm Taupe" },
      { hex: "#9E8C6C", name: "Khaki Brown" },
      { hex: "#BDB76B", name: "Dark Khaki" },
      { hex: "#8F9779", name: "Sage" },
      { hex: "#808000", name: "Olive" },
      { hex: "#556B2F", name: "Dark Olive" },
      { hex: "#6B8E23", name: "Olive Drab" },
      { hex: "#8FBC8F", name: "Dark Sea Green" },
      { hex: "#5F9EA0", name: "Cadet Blue" },
      { hex: "#4682B4", name: "Steel Blue" },
      { hex: "#708090", name: "Slate Gray" },
      { hex: "#CD9B9B", name: "Dusty Rose" },
      { hex: "#C08081", name: "Old Rose" },
      { hex: "#B5651D", name: "Cocoa" },
      { hex: "#D2B48C", name: "Tan" },
      { hex: "#DEB887", name: "Burlywood" },
      { hex: "#F5DEB3", name: "Wheat" },
      { hex: "#E6D8C3", name: "Cream" },
      { hex: "#E6E0D4", name: "Soft Ivory" },
      { hex: "#A0522D", name: "Sienna" },
      { hex: "#CD853F", name: "Peru" },
      { hex: "#8B7355", name: "Light Brown" },
      { hex: "#6B4226", name: "Medium Brown" },
      { hex: "#36454F", name: "Charcoal" }
    ]
  },
  "deep-winter": {
    name: "Deep Winter",
    aliases: ["Dark Winter"],
    description: "Cool, deep, and vivid. Intense dark cool tones.",
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#0C0C0C", name: "Near Black" },
      { hex: "#1C1C1C", name: "Dark Charcoal" },
      { hex: "#2F4F4F", name: "Dark Slate Gray" },
      { hex: "#191970", name: "Midnight Blue" },
      { hex: "#000080", name: "Navy" },
      { hex: "#00008B", name: "Dark Blue" },
      { hex: "#0000CD", name: "Medium Blue" },
      { hex: "#4169E1", name: "Royal Blue" },
      { hex: "#006400", name: "Dark Green" },
      { hex: "#004D40", name: "Deep Teal" },
      { hex: "#008080", name: "Teal" },
      { hex: "#800000", name: "Maroon" },
      { hex: "#8B0000", name: "Dark Red" },
      { hex: "#B22222", name: "Firebrick" },
      { hex: "#DC143C", name: "Crimson" },
      { hex: "#4B0082", name: "Indigo" },
      { hex: "#800080", name: "Purple" },
      { hex: "#8B008B", name: "Dark Magenta" },
      { hex: "#9400D3", name: "Dark Violet" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#FFFFFF", name: "White" },
      { hex: "#F5F5F5", name: "White Smoke" },
      { hex: "#FF0000", name: "True Red" },
      { hex: "#FF1493", name: "Deep Pink" },
      { hex: "#00FF00", name: "Emerald" },
      { hex: "#00FFFF", name: "Cyan" },
      { hex: "#FF00FF", name: "Magenta" },
      { hex: "#FFD700", name: "Gold" },
      { hex: "#483D8B", name: "Dark Slate Blue" }
    ]
  },
  "cool-winter": {
    name: "Cool Winter",
    aliases: ["True Winter"],
    description: "Cool, medium-dark, and clear. Pure cool tones, high contrast.",
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#FFFFFF", name: "White" },
      { hex: "#0000FF", name: "Blue" },
      { hex: "#000080", name: "Navy" },
      { hex: "#4169E1", name: "Royal Blue" },
      { hex: "#1E90FF", name: "Dodger Blue" },
      { hex: "#00BFFF", name: "Deep Sky Blue" },
      { hex: "#87CEEB", name: "Sky Blue" },
      { hex: "#E0F0FF", name: "Ice Blue" },
      { hex: "#FF0000", name: "True Red" },
      { hex: "#DC143C", name: "Crimson" },
      { hex: "#C71585", name: "Medium Violet Red" },
      { hex: "#FF1493", name: "Deep Pink" },
      { hex: "#FF69B4", name: "Hot Pink" },
      { hex: "#FFC0CB", name: "Pink" },
      { hex: "#800080", name: "Purple" },
      { hex: "#4B0082", name: "Indigo" },
      { hex: "#8A2BE2", name: "Blue Violet" },
      { hex: "#9370DB", name: "Medium Purple" },
      { hex: "#E6E6FA", name: "Lavender" },
      { hex: "#006400", name: "Dark Green" },
      { hex: "#228B22", name: "Forest Green" },
      { hex: "#00FF7F", name: "Spring Green" },
      { hex: "#00CED1", name: "Dark Turquoise" },
      { hex: "#2F4F4F", name: "Dark Slate Gray" },
      { hex: "#696969", name: "Dim Gray" },
      { hex: "#808080", name: "Gray" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#483D8B", name: "Dark Slate Blue" },
      { hex: "#F0F8FF", name: "Alice Blue" }
    ]
  },
  "clear-winter": {
    name: "Clear Winter",
    aliases: ["Bright Winter"],
    description: "Cool, bright, and high-contrast. Jewel tones and icy brights.",
    colors: [
      { hex: "#000000", name: "Black" },
      { hex: "#FFFFFF", name: "White" },
      { hex: "#FF0000", name: "True Red" },
      { hex: "#0000FF", name: "True Blue" },
      { hex: "#FFFF00", name: "Bright Yellow" },
      { hex: "#00FF00", name: "Bright Green" },
      { hex: "#FF00FF", name: "Fuchsia" },
      { hex: "#00FFFF", name: "Cyan" },
      { hex: "#FF1493", name: "Deep Pink" },
      { hex: "#FF69B4", name: "Hot Pink" },
      { hex: "#DC143C", name: "Crimson" },
      { hex: "#4169E1", name: "Royal Blue" },
      { hex: "#1E90FF", name: "Dodger Blue" },
      { hex: "#00BFFF", name: "Deep Sky Blue" },
      { hex: "#4B0082", name: "Indigo" },
      { hex: "#8A2BE2", name: "Blue Violet" },
      { hex: "#9400D3", name: "Dark Violet" },
      { hex: "#BA55D3", name: "Medium Orchid" },
      { hex: "#00CED1", name: "Dark Turquoise" },
      { hex: "#20B2AA", name: "Light Sea Green" },
      { hex: "#008B8B", name: "Dark Cyan" },
      { hex: "#228B22", name: "Forest Green" },
      { hex: "#006400", name: "Dark Green" },
      { hex: "#191970", name: "Midnight Blue" },
      { hex: "#000080", name: "Navy" },
      { hex: "#C0C0C0", name: "Silver" },
      { hex: "#808080", name: "Gray" },
      { hex: "#36454F", name: "Charcoal" },
      { hex: "#E0F0FF", name: "Ice Blue" },
      { hex: "#F0F8FF", name: "Alice Blue" }
    ]
  }
};

// --- Season Profiles ---
// Each season's expected color dimensions based on seasonal color analysis theory.
// temperature: -1 (cool) to +1 (warm)
// value: 0 (dark) to 1 (light)
// chroma: 0 (muted) to 1 (bright)
// primary/secondary: the two dominant characteristics (weighted heavier in scoring)
// neighbors: adjacent seasons in the flow model

const SEASON_PROFILES = {
  "light-spring": {
    name: "Light Spring",
    primary: "light",
    secondary: "warm",
    temperature: { ideal: 0.35, min: 0.0, max: 0.7 },
    value: { ideal: 0.75, min: 0.5, max: 0.95 },
    chroma: { ideal: 0.55, min: 0.3, max: 0.8 },
    neighbors: ["warm-spring", "light-summer"]
  },
  "warm-spring": {
    name: "Warm Spring",
    primary: "warm",
    secondary: "bright",
    temperature: { ideal: 0.7, min: 0.3, max: 1.0 },
    value: { ideal: 0.6, min: 0.3, max: 0.85 },
    chroma: { ideal: 0.65, min: 0.35, max: 0.95 },
    neighbors: ["light-spring", "clear-spring", "warm-autumn"]
  },
  "clear-spring": {
    name: "Clear Spring",
    primary: "bright",
    secondary: "warm",
    temperature: { ideal: 0.4, min: 0.0, max: 0.8 },
    value: { ideal: 0.55, min: 0.2, max: 0.9 },
    chroma: { ideal: 0.8, min: 0.55, max: 1.0 },
    neighbors: ["warm-spring", "clear-winter"]
  },
  "light-summer": {
    name: "Light Summer",
    primary: "light",
    secondary: "cool",
    temperature: { ideal: -0.25, min: -0.6, max: 0.1 },
    value: { ideal: 0.75, min: 0.55, max: 0.95 },
    chroma: { ideal: 0.35, min: 0.1, max: 0.55 },
    neighbors: ["light-spring", "cool-summer"]
  },
  "cool-summer": {
    name: "Cool Summer",
    primary: "cool",
    secondary: "muted",
    temperature: { ideal: -0.5, min: -1.0, max: 0.0 },
    value: { ideal: 0.5, min: 0.2, max: 0.8 },
    chroma: { ideal: 0.4, min: 0.15, max: 0.6 },
    neighbors: ["light-summer", "soft-summer", "cool-winter"]
  },
  "soft-summer": {
    name: "Soft Summer",
    primary: "muted",
    secondary: "cool",
    temperature: { ideal: -0.2, min: -0.6, max: 0.15 },
    value: { ideal: 0.45, min: 0.2, max: 0.7 },
    chroma: { ideal: 0.25, min: 0.05, max: 0.45 },
    neighbors: ["cool-summer", "soft-autumn"]
  },
  "soft-autumn": {
    name: "Soft Autumn",
    primary: "muted",
    secondary: "warm",
    temperature: { ideal: 0.2, min: -0.15, max: 0.55 },
    value: { ideal: 0.45, min: 0.2, max: 0.7 },
    chroma: { ideal: 0.25, min: 0.05, max: 0.45 },
    neighbors: ["soft-summer", "warm-autumn"]
  },
  "warm-autumn": {
    name: "Warm Autumn",
    primary: "warm",
    secondary: "muted",
    temperature: { ideal: 0.65, min: 0.3, max: 1.0 },
    value: { ideal: 0.45, min: 0.2, max: 0.7 },
    chroma: { ideal: 0.4, min: 0.15, max: 0.6 },
    neighbors: ["soft-autumn", "deep-autumn", "warm-spring"]
  },
  "deep-autumn": {
    name: "Deep Autumn",
    primary: "dark",
    secondary: "warm",
    temperature: { ideal: 0.45, min: 0.1, max: 0.8 },
    value: { ideal: 0.25, min: 0.05, max: 0.5 },
    chroma: { ideal: 0.5, min: 0.2, max: 0.75 },
    neighbors: ["warm-autumn", "deep-winter"]
  },
  "deep-winter": {
    name: "Deep Winter",
    primary: "dark",
    secondary: "cool",
    temperature: { ideal: -0.35, min: -0.8, max: 0.1 },
    value: { ideal: 0.2, min: 0.0, max: 0.45 },
    chroma: { ideal: 0.55, min: 0.25, max: 0.85 },
    neighbors: ["deep-autumn", "cool-winter"]
  },
  "cool-winter": {
    name: "Cool Winter",
    primary: "cool",
    secondary: "bright",
    temperature: { ideal: -0.55, min: -1.0, max: 0.0 },
    value: { ideal: 0.4, min: 0.05, max: 0.85 },
    chroma: { ideal: 0.7, min: 0.4, max: 1.0 },
    neighbors: ["deep-winter", "clear-winter", "cool-summer"]
  },
  "clear-winter": {
    name: "Clear Winter",
    primary: "bright",
    secondary: "cool",
    temperature: { ideal: -0.4, min: -0.9, max: 0.1 },
    value: { ideal: 0.45, min: 0.05, max: 0.9 },
    chroma: { ideal: 0.8, min: 0.55, max: 1.0 },
    neighbors: ["cool-winter", "clear-spring"]
  }
};

function getSeasonProfile(key) {
  return SEASON_PROFILES[key] || null;
}

// Build lookup map including aliases
function getPaletteByKey(key) {
  return PALETTES[key] || null;
}

function getAllPaletteOptions() {
  const options = [];
  for (const [key, palette] of Object.entries(PALETTES)) {
    options.push({ key, name: palette.name, description: palette.description });
  }
  return options;
}

// Search by name or alias (case-insensitive)
function findPalette(query) {
  const q = query.toLowerCase();
  for (const [key, palette] of Object.entries(PALETTES)) {
    if (palette.name.toLowerCase() === q) return { key, palette };
    for (const alias of palette.aliases) {
      if (alias.toLowerCase() === q) return { key, palette };
    }
  }
  return null;
}
